name: testpatrol
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  patrol: ^2.2.3

flutter:
  uses-material-design: true

patrol:
  app_name: testpatrol
  android:
    package_name: com.example.testpatrol
  ios:
    bundle_id: com.example.testpatrol